//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ProjectAugust1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageTB
    {
        public int EmailId { get; set; }
        public System.TimeSpan EmailTime { get; set; }
        public System.DateTime EmailDate { get; set; }
        public string EmailText { get; set; }
        public string EmailTo { get; set; }
        public string EmailFrom { get; set; }
    }
}
